name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - spyder
  - python=3
  - geopandas
  - matplotlib
  - descartes
  - contextily
  - dash
  - folium
  - voila
  - bqplot
  - voila-gridstack

